'''title'''
__title__ = 'downloader'
'''description'''
__description__ = 'music downloader mainly migu'
'''version'''
__version__ = '0.0.1'
'''author'''
__author__ = 'David'
'''license'''
__license__ = 'MIT License'
'''copyright'''
__copyright__ = 'Music copyright to music provider'